### ISSUE TITLE
Should we use bootstrap or semantic ui as default?

### ISSUE THREAD

**Issue by d0minicw0ng** [opsmanager/jquery.uploadPreviewer.js#1]
We chose semantic ui in the first go, but most people out there use bootstrap. We should go with the one that most people use so it's less custom configurations for them right?

**Comment by jasonm23** [comment]
Yes

**Comment by jasonm23** [comment]
Please also add a README

**Comment by d0minicw0ng** [comment]
@jasonm23 I added a README in my branch.
